    expect(famicomHud).toContain("onSave");
    expect(famicomHud).toContain("onLoad");
    expect(famicomHud).toContain("onExit");
    expect(famicomHud).toContain("onEditLayout");
    expect(famicomHud).toContain("EDIT CONTROLS & SCREEN");
    expect(famicomRoom).toContain("screenPanResponder.panHandlers");
    expect(famicomRoom).toContain("onEditLayout={() => { setFocusMode(true); setFocusControlEditor(true);");
    expect(famicomRoom).toContain("moudie.famicom.screen.v1.${startOrientation}");
    expect(controller).not.toContain("Math.max(0, Math.min(100");
    expect(controller).not.toContain("Math.max(30, Math.min(94");
    expect(module).toContain('AsyncFunction("prepareNativeCore")');
    expect(module).toContain('AsyncFunction("prepareFastLaunch")');
    expect(module).toContain('val sourceKey = MessageDigest.getInstance("SHA-256")');
    expect(moduleBridge).toContain("prepareFastLaunch(system: EmulatorSystem");
    expect(ps1).toContain("createFreeControlCanvas()");
    expect(ps1).toContain("retroView.setOnTouchListener");
    expect(famicom).toContain("retroView.setOnTouchListener");
    expect(library).not.toContain("CHOOSE FILE & CONFIGURE");
    expect(famicomRoom).toContain('nativePlayerRef.current?.requestState("netplay")');
    expect(oauth).toContain("const NATIVE_API_FALLBACK_URL = NATIVE_NETPLAY_SERVICE_URL");
    expect(ps1).toContain('RENDERMODE_CONTINUOUSLY');
    // Reconnection is intentionally persistent for long mobile outages; the
    // client uses a bounded exponential backoff rather than abandoning a room.
    expect(ps1Client).toMatch(/reconnectionAttempts = (12|20|30|50|Integer\.MAX_VALUE)/);
    expect(ps1Client).toMatch(/reconnectionDelayMax = (2_000|3_000|4_000|8_000)/);
    expect(ps1Client).toContain('transports = arrayOf("websocket", "polling")');
    expect(ps1Client).toContain('NetplayQualityMonitor');
    expect(universalClient).toMatch(/reconnectionAttempts = (12|20|30|50|Integer\.MAX_VALUE)/);
    expect(universalClient).toMatch(/reconnectionDelayMax = (2_000|3_000|4_000|8_000)/);
    expect(universalClient).toContain('transports = arrayOf("websocket", "polling")');
    expect(universalClient).toContain('NetplayQualityMonitor');
    expect(universalClient).toContain('path = "/api/netplay"');
    expect(universalClient).toContain('"clientKind" to "universal-player"');
    expect(universalClient).toContain('"netplay:universal-ready"');
    expect(universalClient).toContain('"netplay:universal-session-bootstrap"');
    expect(universalClient).toContain('"netplay:universal-session-go"');
    expect(universalClient).toContain('"netplay:quality-probe"');
    expect(ps1Room).toContain("prepareFastLaunch(\"ps1\"");
    expect(nativeRoom).toContain("prepareFastLaunch(system as EmulatorSystem");
  });
});